In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import typer
import sys
from pathlib import Path

# Add the parent directory of 'data_master_eng_ml' to sys.path
sys.path.append(str(Path.cwd().parent))
from typing import List
from loguru import logger
from typing import Dict
from data_master_eng_ml.config import DUCKDB_PATH


from data_master_eng_ml.utils.helpers import (
    save_to_duckdb,
    get_unix_timestamp_for_year_start,
)

import pandas as pd

app = typer.Typer()
from data_master_eng_ml.utils.auth_igdb import IGDBAuthenticatedClient
from data_master_eng_ml.utils.api_igdb import (
    build_query,
    fetch_data_with_pagination,
)
from data_master_eng_ml.schemas.api_schemas import (
    GamesSchema,
    PlatformSchema,
    GenreSchema,
    PlayerPerspectiveSchema,
    AgeContentDescriptionSchema,
    AgeRatingSchema,
    CompaniesSchema,
    GamesModesSchema,
    LanguageSupportSchema,
    ThemeSchema,
)

2025-04-13 23:27:02.653 | INFO     | data_master_eng_ml.config:<module>:12 - Diretório raiz do projeto: /Users/josepaulo/data_master_eng_ml

2025-04-13 23:27:03.238 | INFO     | data_master_eng_ml.utils.auth_igdb:get_valid_token:82 - Token expirado ou inexistente. Obtendo um novo...
2025-04-13 23:27:04.289 | INFO     | data_master_eng_ml.utils.auth_igdb:get_token:67 - Novo token obtido com sucesso.

In [3]:
import duckdb

In [4]:
DUCKDB_PATH

PosixPath('/Users/josepaulo/data_master_eng_ml/db/duckdb/datamaster.db')

In [5]:
# Connect to the DuckDB database
with duckdb.connect("file.db") as con:
    # Save the DataFrame to the specified table
    df_games = con.sql("select * from raw_games").df()

In [24]:
# Connect to the DuckDB database
with duckdb.connect("file.db") as con:
    # Save the DataFrame to the specified table
    df_games = con.sql("show tables").show()

┌─────────────────────────────────────┐
│                name                 │
│               varchar               │
├─────────────────────────────────────┤
│ raw_age_rating_content_descriptions │
│ raw_age_ratings                     │
│ raw_companies                       │
│ raw_game_modes                      │
│ raw_games                           │
│ raw_genres                          │
│ raw_languages                       │
│ raw_platforms                       │
│ raw_player_perspectives             │
│ raw_themes                          │
├─────────────────────────────────────┤
│               10 rows               │
└─────────────────────────────────────┘

In [28]:
# Connect to the DuckDB database
with duckdb.connect("file.db") as con:
    # Save the DataFrame to the specified table
    df_games = con.sql("select id, name from raw_player_perspectives").show()

┌───────┬───────────────────────┐
│  id   │         name          │
│ int64 │        varchar        │
├───────┼───────────────────────┤
│     1 │ First person          │
│     2 │ Third person          │
│     3 │ Bird view / Isometric │
│     4 │ Side view             │
│     5 │ Text                  │
│     6 │ Auditory              │
│     7 │ Virtual Reality       │
└───────┴───────────────────────┘

In [ ]:
# Connect to the DuckDB database
with duckdb.connect("file.db") as con:
    # Save the DataFrame to the specified table
    df_games = con.sql("select id, name from raw_game_modes").show()

┌───────┬────────────────────────────────────┐
│  id   │                name                │
│ int64 │              varchar               │
├───────┼────────────────────────────────────┤
│     1 │ Single player                      │
│     2 │ Multiplayer                        │
│     3 │ Co-operative                       │
│     4 │ Split screen                       │
│     5 │ Massively Multiplayer Online (MMO) │
│     6 │ Battle Royale                      │
└───────┴────────────────────────────────────┘

In [ ]:
# Connect to the DuckDB database
with duckdb.connect("file.db") as con:
    # Save the DataFrame to the specified table
    df_games = con.sql("select id, name from raw_genres").show()

┌───────┬────────────────────────────┐
│  id   │            name            │
│ int64 │          varchar           │
├───────┼────────────────────────────┤
│     2 │ Point-and-click            │
│     4 │ Fighting                   │
│     5 │ Shooter                    │
│     7 │ Music                      │
│     8 │ Platform                   │
│     9 │ Puzzle                     │
│    10 │ Racing                     │
│    11 │ Real Time Strategy (RTS)   │
│    12 │ Role-playing (RPG)         │
│    13 │ Simulator                  │
│    14 │ Sport                      │
│    15 │ Strategy                   │
│    16 │ Turn-based strategy (TBS)  │
│    24 │ Tactical                   │
│    25 │ Hack and slash/Beat 'em up │
│    26 │ Quiz/Trivia                │
│    30 │ Pinball                    │
│    31 │ Adventure                  │
│    32 │ Indie                      │
│    33 │ Arcade                     │
│    34 │ Visual Novel               │
│    35 │ Card & Board Game          │
│    36 │ MOBA                       │
├───────┴────────────────────────────┤
│ 23 rows                  2 columns │
└────────────────────────────────────┘

In [6]:
df_games

,id,artworks,category,cover,created_at,external_games,first_release_date,game_engines,game_modes,genres,...,age_ratings,aggregated_rating,aggregated_rating_count,involved_companies,franchise,franchises,rating,rating_count,remakes,remasters
0,240146,[103535],0,290071.0,1677669793,"[2674780, 2680022]",1677196800,[13],[1],"[32, 33]",...,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN
1,216659,[86261],0,431088.0,1663009535,"[2994556, 2567665, 2566112]",1736294400,<NA>,[1],"[9, 31]",...,"[197611, 197745]",NaN,NaN,[305758],<NA>,NaN,NaN,NaN,NaN,NaN
2,314239,"[153505, 153506, 153507]",0,437797.0,1724175649,"[2940851, 2979689, 2940710]",1747699200,<NA>,"[1, 2, 3]","[13, 31]",...,[197017],NaN,NaN,"[282793, 282794]",<NA>,NaN,NaN,NaN,NaN,NaN
3,274434,[121575],3,343685.0,1698739889,"[2857088, 2857108]",1698364800,<NA>,<NA>,<NA>,...,"[157922, 157924, 157926, 157923, 157925]",NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN
4,260316,[116837],13,328181.0,1691337413,"[2739152, 2729322]",1693526400,<NA>,[1],"[12, 15]",...,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50196,282334,<NA>,5,410182.0,1704904956,<NA>,1699574400,<NA>,[1],[8],...,<NA>,NaN,NaN,[247787],<NA>,NaN,NaN,NaN,NaN,NaN
50197,241082,[120026],0,336492.0,1678267774,"[2862142, 2752173, 2867337, 2682101, 2682118, ...",1699920000,<NA>,[1],"[31, 33]",...,"[159554, 159552, 159434, 159553, 159551, 16126...",NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN
50198,152424,[41184],0,288563.0,1623883743,"[2063712, 2686280, 2687516, 2873769, 2680277, ...",1679961600,[13],[1],"[9, 13, 15, 32]",...,"[132169, 139957, 164308, 129373, 164555]",80.0,1.0,"[196262, 196263, 204913, 261039, 287193]",<NA>,NaN,73.318709,38.0,NaN,NaN
50199,324930,[150194],1,426091.0,1733770685,"[2943831, 2943251]",1729728000,<NA>,[1],"[13, 15]",...,<NA>,NaN,NaN,[298841],<NA>,NaN,NaN,NaN,NaN,NaN
50200,199447,[75291],0,248226.0,1651504069,"[2623660, 2436780, 2924707, 2435557]",1719014400,<NA>,"[1, 2, 3]","[5, 7, 32, 33]",...,"[137404, 137407, 137405, 137408, 137406]",NaN,NaN,[197354],<NA>,NaN,NaN,NaN,NaN,NaN

In [7]:
"""
Cell generated by Data Wrangler.
"""


def clean_data(df_games):
    # Extract year from first_release_date
    df_games["year_of_first_release"] = pd.to_datetime(
        df_games["first_release_date"], unit="s"
    ).dt.year
    df_games["summary_size"] = df_games["summary"].str.len()
    return df_games


df_games_clean = clean_data(df_games.copy())
df_games_clean.head()

,id,artworks,category,cover,created_at,external_games,first_release_date,game_engines,game_modes,genres,...,aggregated_rating_count,involved_companies,franchise,franchises,rating,rating_count,remakes,remasters,year_of_first_release,summary_size
0,240146,[103535],0,290071.0,1677669793,"[2674780, 2680022]",1677196800,[13],[1],"[32, 33]",...,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,2023,630.0
1,216659,[86261],0,431088.0,1663009535,"[2994556, 2567665, 2566112]",1736294400,<NA>,[1],"[9, 31]",...,NaN,[305758],<NA>,<NA>,NaN,NaN,<NA>,<NA>,2025,274.0
2,314239,"[153505, 153506, 153507]",0,437797.0,1724175649,"[2940851, 2979689, 2940710]",1747699200,<NA>,"[1, 2, 3]","[13, 31]",...,NaN,"[282793, 282794]",<NA>,<NA>,NaN,NaN,<NA>,<NA>,2025,249.0
3,274434,[121575],3,343685.0,1698739889,"[2857088, 2857108]",1698364800,<NA>,<NA>,<NA>,...,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,2023,261.0
4,260316,[116837],13,328181.0,1691337413,"[2739152, 2729322]",1693526400,<NA>,[1],"[12, 15]",...,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,2023,66.0

In [18]:
# Mapeamento usando os IDs
genres_group_map = {
    4: "Action",
    5: "Action",
    25: "Action",
    36: "Action",
    8: "Action",
    33: "Action",
    11: "Strategy",
    16: "Strategy",
    15: "Strategy",
    24: "Strategy",
    35: "Strategy",
    9: "Puzzle",
    26: "Puzzle",
    13: "Simulation",
    14: "Simulation",
    10: "Simulation",
    30: "Simulation",
    31: "Narrative",
    2: "Narrative",
    34: "Narrative",
    12: "Narrative",
    32: "Creative",
    7: "Creative",
}

In [27]:
game_mode_groups = {
    1: "Solo",
    2: "Multiplayer",
    3: "Co-op",
    4: "Co-op",
    5: "MMO",
    6: "Battle Royale",
}

In [8]:
import numpy as np


def contar_elementos(x):
    # Se for um array NumPy, retorna o tamanho dele
    if isinstance(x, np.ndarray):
        return x.size

    # Se for nulo ou não for uma string ou lista, retorne 0
    # Note que pd.isna(x) não deve ser usada diretamente se x for um array!
    if pd.isna(x):
        return 0

    # Se for uma lista (real), conta seus elementos
    if isinstance(x, list):
        return len(x)

    # Se for uma string, processa-a
    if isinstance(x, str):
        texto = x.strip()  # remove espaços no início e fim
        if texto in ("[]", "[ ]"):  # caso de string vazia entre colchetes
            return 0
        # Remove os colchetes e espaços extras
        conteudo = texto.strip("[]").strip()
        if conteudo == "":
            return 0
        # Separa os elementos usando espaços (ajuste se os elementos forem separados por vírgulas)
        elementos = conteudo.split()
        return len(elementos)

    # Se não se enquadrar em nenhum dos casos anteriores, retorna 0
    return 0

In [9]:
df_games_clean["release_dates_counts"] = df_games_clean["release_dates"].apply(
    contar_elementos
)
df_games_clean["player_perspectives_counts"] = df_games_clean[
    "player_perspectives"
].apply(contar_elementos)
df_games_clean["screenshots_counts"] = df_games_clean["screenshots"].apply(
    contar_elementos
)
df_games_clean["similar_games_counts"] = df_games_clean["similar_games"].apply(
    contar_elementos
)
df_games_clean["platforms_counts"] = df_games_clean["platforms"].apply(contar_elementos)
df_games_clean["language_supports_counts"] = df_games_clean["language_supports"].apply(
    contar_elementos
)
df_games_clean["websites_counts"] = df_games_clean["websites"].apply(contar_elementos)
df_games_clean["themes_counts"] = df_games_clean["themes"].apply(contar_elementos)
df_games_clean["artworks_counts"] = df_games_clean["artworks"].apply(contar_elementos)
df_games_clean["external_games_counts"] = df_games_clean["external_games"].apply(
    contar_elementos
)
df_games_clean["tags_counts"] = df_games_clean["tags"].apply(contar_elementos)
df_games_clean["videos_counts"] = df_games_clean["videos"].apply(contar_elementos)

In [29]:
player_perspective_groups = {
    1: "Immersive",
    2: "Third person",
    3: "Strategic view",
    4: "Side view",
    5: "Text-based",
    6: "Auditory",
    7: "Immersive",
}

In [10]:
suport_columns = [
    "checksum",
    "first_release_date",
    "updated_at",
    "url",
    "created_at",
    "cover",
    "keywords",
]

In [11]:
columns_to_drop = [
    "screenshots",
    "similar_games",
    "platforms",
    "language_supports",
    "websites",
    "themes",
    "artworks",
    "external_games",
    "tags",
    "videos",
    "player_perspectives",
    "release_dates",
    "summary",
]

df_games_clean = df_games_clean.drop(columns=columns_to_drop + suport_columns)
df_games_clean

,id,category,game_engines,game_modes,genres,name,slug,status,game_status,game_type,...,screenshots_counts,similar_games_counts,platforms_counts,language_supports_counts,websites_counts,themes_counts,artworks_counts,external_games_counts,tags_counts,videos_counts
0,240146,0,[13],[1],"[32, 33]",Boom,boom--4,4.0,4.0,0,...,9,10,2,6,4,1,1,2,4,1
1,216659,0,<NA>,[1],"[9, 31]",Discolored 2,discolored-2,NaN,NaN,0,...,10,10,3,17,6,0,1,3,3,3
2,314239,0,<NA>,"[1, 2, 3]","[13, 31]",RoadCraft,roadcraft,NaN,NaN,0,...,9,10,3,31,7,0,3,3,2,3
3,274434,3,<NA>,<NA>,<NA>,Merge Games Horror Bundle,merge-games-horror-bundle,NaN,NaN,3,...,1,0,2,0,0,0,1,2,0,0
4,260316,13,<NA>,[1],"[12, 15]",Banners of Ruin: Iris,banners-of-ruin-iris,NaN,NaN,13,...,4,10,1,20,3,0,1,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50196,282334,5,<NA>,[1],[8],#0 Iggy's Castle,number-0-iggys-castle,NaN,NaN,5,...,2,10,1,1,1,1,0,0,3,1
50197,241082,0,<NA>,[1],"[31, 33]",UFO Robot Grendizer: The Feast of the Wolves -...,ufo-robot-grendizer-the-feast-of-the-wolves-de...,NaN,NaN,0,...,5,10,4,15,1,1,1,10,2,1
50198,152424,0,[13],[1],"[9, 13, 15, 32]",Terra Nil,terra-nil--1,NaN,NaN,0,...,10,10,6,33,16,3,1,8,13,6
50199,324930,1,<NA>,[1],"[13, 15]",Distant Worlds 2: Return of the Shakturi,distant-worlds-2-return-of-the-shakturi,NaN,NaN,1,...,19,10,1,3,4,2,1,2,3,0
50200,199447,0,<NA>,"[1, 2, 3]","[5, 7, 32, 33]",Beat Hazard 3,beat-hazard-3,NaN,NaN,0,...,11,10,1,10,9,1,1,4,7,1

In [22]:
# Função segura que lida com np.array e valores nulos
def map_genres(id_array):
    if isinstance(id_array, (np.ndarray, list)):
        return [
            genres_group_map.get(i)
            for i in id_array
            if genres_group_map.get(i) is not None
        ]
    else:
        return None

In [23]:
df_games_clean["genre_groups"] = df_games_clean["genres"].apply(map_genres)
df_games_clean

,id,category,game_engines,game_modes,genres,name,slug,status,game_status,game_type,...,similar_games_counts,platforms_counts,language_supports_counts,websites_counts,themes_counts,artworks_counts,external_games_counts,tags_counts,videos_counts,genre_groups
0,240146,0,[13],[1],"[32, 33]",Boom,boom--4,4.0,4.0,0,...,10,2,6,4,1,1,2,4,1,"[Creative, Action]"
1,216659,0,<NA>,[1],"[9, 31]",Discolored 2,discolored-2,NaN,NaN,0,...,10,3,17,6,0,1,3,3,3,"[Puzzle, Narrative]"
2,314239,0,<NA>,"[1, 2, 3]","[13, 31]",RoadCraft,roadcraft,NaN,NaN,0,...,10,3,31,7,0,3,3,2,3,"[Simulation, Narrative]"
3,274434,3,<NA>,<NA>,<NA>,Merge Games Horror Bundle,merge-games-horror-bundle,NaN,NaN,3,...,0,2,0,0,0,1,2,0,0,None
4,260316,13,<NA>,[1],"[12, 15]",Banners of Ruin: Iris,banners-of-ruin-iris,NaN,NaN,13,...,10,1,20,3,0,1,2,2,1,"[Narrative, Strategy]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50196,282334,5,<NA>,[1],[8],#0 Iggy's Castle,number-0-iggys-castle,NaN,NaN,5,...,10,1,1,1,1,0,0,3,1,[Action]
50197,241082,0,<NA>,[1],"[31, 33]",UFO Robot Grendizer: The Feast of the Wolves -...,ufo-robot-grendizer-the-feast-of-the-wolves-de...,NaN,NaN,0,...,10,4,15,1,1,1,10,2,1,"[Narrative, Action]"
50198,152424,0,[13],[1],"[9, 13, 15, 32]",Terra Nil,terra-nil--1,NaN,NaN,0,...,10,6,33,16,3,1,8,13,6,"[Puzzle, Simulation, Strategy, Creative]"
50199,324930,1,<NA>,[1],"[13, 15]",Distant Worlds 2: Return of the Shakturi,distant-worlds-2-return-of-the-shakturi,NaN,NaN,1,...,10,1,3,4,2,1,2,3,0,"[Simulation, Strategy]"
50200,199447,0,<NA>,"[1, 2, 3]","[5, 7, 32, 33]",Beat Hazard 3,beat-hazard-3,NaN,NaN,0,...,10,1,10,9,1,1,4,7,1,"[Action, Creative, Creative, Action]"