In [1]:
# check installed version
import pycaret
pycaret.__version__

'3.3.2'

In [2]:
from data_master_eng_ml.utils.helpers import read_data_from_mongodb

2025-02-17 21:31:10.712 | INFO     | data_master_eng_ml.config:<module>:12 - Diretório raiz do projeto: /home/jose/data_master_eng_ml

2025-02-17 21:31:11.052 | INFO     | data_master_eng_ml.utils.auth_igdb:get_valid_token:76 - Token expirado ou inexistente. Obtendo um novo...
2025-02-17 21:31:12.089 | INFO     | data_master_eng_ml.utils.auth_igdb:get_token:61 - Novo token obtido com sucesso.
2025-02-17 21:31:14.183 | INFO     | data_master_eng_ml.db.mongodb_client:__init__:32 - Connected to MongoDB at mongodb://root:example@localhost:27017/, database: datamasterml

In [3]:
from data_master_eng_ml.config import GAMES_SILVER_COLLECTION,MONGODB_DEFAULT_DATABASE

In [4]:
df_2022 = read_data_from_mongodb(MONGODB_DEFAULT_DATABASE,GAMES_SILVER_COLLECTION)

In [5]:
df_2022

,id,name,dat_ref,genres_first,has_remaster,target,age_rating_group,games_developed,has_parents,games_published,...,unknown_game_mode,auditory,bird_view_slash_isometric,first_person,side_view,text,third_person,unknown_player_perspectives,virtual_reality,has_global_launch
0,71,Portal,2022,shooter,False,1,15+,126.0,0.0,1397.0,...,0,0,0,1,0,0,0,0,0,1
1,72,Portal 2,2022,adventure,False,1,12+,87.0,0.0,95.0,...,0,0,0,1,0,0,0,0,0,1
2,4250,Kingdom: The Far Reaches,2022,adventure,False,0,12+,5.0,0.0,43.0,...,0,0,0,0,0,0,1,0,0,1
3,6614,Zero Escape: Virtue's Last Reward,2022,point-and-click,False,1,18+,1.0,0.0,132.0,...,0,0,0,1,0,1,0,0,0,1
4,7046,Factorio,2022,strategy,False,1,12+,2.0,0.0,2.0,...,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2157,325870,Lucky Pikinini: Zombie Rampage,2022,shooter,False,0,No Rating,NaN,NaN,NaN,...,0,0,0,1,0,0,0,0,0,0
2158,303265,Would You Sell Your Soul? 2,2022,simulator,False,0,No Rating,24.0,0.0,1.0,...,0,0,0,0,1,1,0,0,0,1
2159,283765,Run and Gun,2022,shooter,False,0,No Rating,NaN,NaN,NaN,...,1,0,0,0,0,0,0,1,0,0
2160,307690,Tamaghost Jump!I Can't Believe It's Not Exorcism!,2022,visual-novel,False,0,No Rating,1.0,0.0,1.0,...,0,0,0,0,1,1,0,0,0,1
2161,284282,The Jiang Shi,2022,adventure,False,0,No Rating,NaN,NaN,NaN,...,1,0,0,0,0,0,0,1,0,0

In [6]:
df_2022['continent_name'] = df_2022['continent_name'].str.replace(' ', '_')
df_2022['age_rating_group'] = df_2022['age_rating_group'].str.replace(' ', '_')

In [7]:
df_2022

,id,name,dat_ref,genres_first,has_remaster,target,age_rating_group,games_developed,has_parents,games_published,...,unknown_game_mode,auditory,bird_view_slash_isometric,first_person,side_view,text,third_person,unknown_player_perspectives,virtual_reality,has_global_launch
0,71,Portal,2022,shooter,False,1,15+,126.0,0.0,1397.0,...,0,0,0,1,0,0,0,0,0,1
1,72,Portal 2,2022,adventure,False,1,12+,87.0,0.0,95.0,...,0,0,0,1,0,0,0,0,0,1
2,4250,Kingdom: The Far Reaches,2022,adventure,False,0,12+,5.0,0.0,43.0,...,0,0,0,0,0,0,1,0,0,1
3,6614,Zero Escape: Virtue's Last Reward,2022,point-and-click,False,1,18+,1.0,0.0,132.0,...,0,0,0,1,0,1,0,0,0,1
4,7046,Factorio,2022,strategy,False,1,12+,2.0,0.0,2.0,...,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2157,325870,Lucky Pikinini: Zombie Rampage,2022,shooter,False,0,No_Rating,NaN,NaN,NaN,...,0,0,0,1,0,0,0,0,0,0
2158,303265,Would You Sell Your Soul? 2,2022,simulator,False,0,No_Rating,24.0,0.0,1.0,...,0,0,0,0,1,1,0,0,0,1
2159,283765,Run and Gun,2022,shooter,False,0,No_Rating,NaN,NaN,NaN,...,1,0,0,0,0,0,0,1,0,0
2160,307690,Tamaghost Jump!I Can't Believe It's Not Exorcism!,2022,visual-novel,False,0,No_Rating,1.0,0.0,1.0,...,0,0,0,0,1,1,0,0,0,1
2161,284282,The Jiang Shi,2022,adventure,False,0,No_Rating,NaN,NaN,NaN,...,1,0,0,0,0,0,0,1,0,0

In [9]:
# import ClassificationExperiment and init the class
from pycaret.classification import ClassificationExperiment
balenced_exp = ClassificationExperiment()

In [ ]:
import mlflow 
mlflow.set_tracking_uri('file:/c:/users/mlflow-server')

In [16]:
# init setup on exp
balenced_exp.setup(
    df_2022,
    target="target",
    session_id=123,
    log_experiment="mlflow",
    experiment_name="balenced_experiment",
    fold=5,
    log_data=True,
    imputation_type="simple",
    log_plots=True,
    # fix_imbalance=True,
    ignore_features=["id", "name","dat_ref"],
    categorical_features=["continent_name","age_rating_group","genres_first"],
    feature_selection=True,
)

[LightGBM] [Info] Number of positive: 125, number of negative: 1388
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001899 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 251
[LightGBM] [Info] Number of data points in the train set: 1513, number of used features: 55
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.082617 -> initscore=-2.407305
[LightGBM] [Info] Start training from score -2.407305

2025/02/17 21:43:49 INFO mlflow.tracking.fluent: Experiment with name 'balenced_experiment' does not exist. Creating a new experiment.

In [ ]:
# compare baseline models
best = balenced_exp.compare_models(include=['xgboost','rf','lr'],sort='AUC')

Initiated  . . . . . . . . . . . . . . . . . .                   21:44:23
Status     . . . . . . . . . . . . . . . . . .            Fitting 5 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Extreme Gradient Boosting

Empty DataFrame
Columns: [Model, Accuracy, AUC, Recall, Prec., F1, Kappa, MCC, TT (Sec)]
Index: []

Processing:   0%|          | 0/17 [00:00<?, ?it/s]

In [9]:
class_exp.evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [10]:
# predict on test set
class_exp.predict_model(best)

,genres_first,has_remaster,age_classif,games_developed,has_parents,games_published,continent_name,onlinecoop,onlinecoopmax,onlinemax,...,first_person,side_view,text,third_person,unknown_player_perspectives,virtual_reality,has_global_launch,target,prediction_label,prediction_score
677,visual-novel,0,No_Rating,17.0,0.0,16.0,Europe,NaN,NaN,NaN,...,0,0,1,0,0,0,1,0,0,0.6966
608,adventure,0,No_Rating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,0,0.8967
283,indie,0,No_Rating,1.0,0.0,1.0,Unknown,NaN,NaN,NaN,...,0,1,0,0,0,0,1,0,0,0.8843
481,platform,0,No_Rating,1.0,0.0,1.0,Unknown,0.0,NaN,NaN,...,0,1,0,0,0,0,1,0,0,0.8843
311,visual-novel,0,No_Rating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,0,0,1,0,0,0,0,0,0.8967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,strategy,0,16+,10.0,1.0,-1.0,North_America,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,1,0.9469
641,hack-and-slash-beat-em-up,0,No_Rating,1.0,0.0,1.0,Asia,NaN,NaN,NaN,...,0,1,0,0,0,0,0,0,0,0.6953
952,unknown_genres_name,0,No_Rating,3.0,0.0,1.0,Unknown,NaN,NaN,NaN,...,0,0,0,0,1,0,1,0,0,0.8769
523,role-playing-rpg,0,12+,1.0,0.0,1.0,Unknown,NaN,NaN,NaN,...,0,0,0,0,1,0,1,1,0,0.8717
895,adventure,0,No_Rating,35.0,0.0,33.0,Europe,NaN,NaN,NaN,...,1,0,0,0,0,0,1,0,0,0.7609

In [11]:
df_api_new = pd.read_csv('twitch_api_data_2022.csv')
df_api_new['continent_name'] = df_api_new['continent_name'].str.replace(' ', '_')
df_api_new['age_classif'] = df_api_new['age_classif'].str.replace(' ', '_')

In [14]:
class_exp.predict_model(best,raw_score=True)

,genres_first,has_remaster,age_classif,games_developed,has_parents,games_published,continent_name,onlinecoop,onlinecoopmax,onlinemax,...,side_view,text,third_person,unknown_player_perspectives,virtual_reality,has_global_launch,target,prediction_label,prediction_score_0,prediction_score_1
677,visual-novel,0,No_Rating,17.0,0.0,16.0,Europe,NaN,NaN,NaN,...,0,1,0,0,0,1,0,0,0.6966,0.3034
608,adventure,0,No_Rating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,1,0,0,0,0,0.8967,0.1033
283,indie,0,No_Rating,1.0,0.0,1.0,Unknown,NaN,NaN,NaN,...,1,0,0,0,0,1,0,0,0.8843,0.1157
481,platform,0,No_Rating,1.0,0.0,1.0,Unknown,0.0,NaN,NaN,...,1,0,0,0,0,1,0,0,0.8843,0.1157
311,visual-novel,0,No_Rating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,1,0,0,0,0,0,0.8967,0.1033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,strategy,0,16+,10.0,1.0,-1.0,North_America,NaN,NaN,NaN,...,0,0,0,0,0,0,0,1,0.0531,0.9469
641,hack-and-slash-beat-em-up,0,No_Rating,1.0,0.0,1.0,Asia,NaN,NaN,NaN,...,1,0,0,0,0,0,0,0,0.6953,0.3047
952,unknown_genres_name,0,No_Rating,3.0,0.0,1.0,Unknown,NaN,NaN,NaN,...,0,0,0,1,0,1,0,0,0.8769,0.1231
523,role-playing-rpg,0,12+,1.0,0.0,1.0,Unknown,NaN,NaN,NaN,...,0,0,0,1,0,1,1,0,0.8717,0.1283
895,adventure,0,No_Rating,35.0,0.0,33.0,Europe,NaN,NaN,NaN,...,0,0,0,0,0,1,0,0,0.7609,0.2391

In [15]:
class_exp.predict_model(best, data=df_api_new,raw_score=True)

,id,name,genres_first,has_remaster,age_classif,games_developed,has_parents,games_published,continent_name,onlinecoop,...,side_view,text,third_person,unknown_player_perspectives,virtual_reality,has_global_launch,target,prediction_label,prediction_score_0,prediction_score_1
0,71,Portal,shooter,0,15+,125.0,0.0,1346.0,North_America,NaN,...,0,0,0,0,0,1,1,1,0.0005,0.9995
1,72,Portal 2,shooter,0,12+,86.0,0.0,94.0,North_America,1.0,...,0,0,0,0,0,1,1,1,0.2637,0.7363
2,1344,Wild Guns,arcade,1,12+,12.0,0.0,36.0,Europe,0.0,...,0,0,1,0,0,0,1,1,0.0800,0.9200
3,4250,Kingdom: The Far Reaches,adventure,0,12+,4.0,0.0,39.0,Unknown,NaN,...,0,0,1,0,0,1,0,0,0.8527,0.1473
4,6614,Zero Escape: Virtue's Last Reward,visual-novel,0,18+,1.0,0.0,132.0,Europe,NaN,...,0,1,0,0,0,1,1,1,0.0359,0.9641
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1300,225446,Dropship Commander,arcade,0,All_Ages,3.0,0.0,3.0,North_America,NaN,...,1,0,0,0,1,1,0,1,0.0880,0.9120
1301,250264,Tokyo Pinball,arcade,0,No_Rating,1.0,0.0,1.0,Unknown,NaN,...,0,0,0,0,0,1,0,0,0.7859,0.2141
1302,307160,Tanuki Tales,arcade,0,No_Rating,1.0,0.0,-1.0,Unknown,NaN,...,0,0,1,0,0,1,0,0,0.8730,0.1270
1303,229164,Cubic Light,indie,0,3+,NaN,NaN,NaN,NaN,NaN,...,0,0,0,1,0,0,0,1,0.2950,0.7050
1304,287629,Toy Story 3,adventure,0,All_Ages,31.0,0.0,-1.0,Europe,NaN,...,0,0,1,0,0,1,0,1,0.1464,0.8536

In [ ]:
final_best = finalize_model(best)

2025/02/16 18:57:45 WARNING mlflow.models.model: Input example should be provided to infer model signature if the model signature is not provided when logging the model.

In [33]:
# save pipeline
save_model(best, 'my_first_pipeline')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['has_remaster', 'games_developed',
                                              'has_parents', 'games_published',
                                              'onlinecoop', 'onlinecoopmax',
                                              'onlinemax', 'splitscreen',
                                              'classic_console',
                                              'less_common_portable_console',
                                              'mobile', 'modern_console',
                                              'others', 'pc', 'portable_console',
                                              'unknown_platfo...
                                                                 importance_getter='auto',
                                                                 max_features=7,
                                                                 norm_order=1,
                                                                 prefit=False,
                                                                 threshold=-inf))),
                 ('trained_model',
                  LogisticRegression(C=1.0, class_weight=None, dual=False,
                                     fit_intercept=True, intercept_scaling=1,
                                     l1_ratio=None, max_iter=1000,
                                     multi_class='auto', n_jobs=None,
                                     penalty='l2', random_state=123,
                                     solver='lbfgs', tol=0.0001, verbose=0,
                                     warm_start=False))],
          verbose=False),
 'my_first_pipeline.pkl')

In [ ]:
# predict model on new_data
predictions = predict_model(best, data = new_data)
predictions.head()

,Number of times pregnant,Plasma glucose concentration a 2 hours in an oral glucose tolerance test,Diastolic blood pressure (mm Hg),Triceps skin fold thickness (mm),2-Hour serum insulin (mu U/ml),Body mass index (weight in kg/(height in m)^2),Diabetes pedigree function,Age (years),prediction_label,prediction_score
0,6,148,72,35,0,33.599998,0.627,50,1,0.6940
1,1,85,66,29,0,26.600000,0.351,31,0,0.9419
2,8,183,64,0,0,23.299999,0.672,32,1,0.7976
3,1,89,66,23,94,28.100000,0.167,21,0,0.9454
4,0,137,40,35,168,43.099998,2.288,33,1,0.8394

In [ ]:
final_best = finalize_model(best)

2025/02/16 17:44:34 WARNING mlflow.models.model: Input example should be provided to infer model signature if the model signature is not provided when logging the model.

In [ ]:
final_best

Pipeline(memory=Memory(location=None),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Number of times pregnant',
                                             'Plasma glucose concentration a 2 '
                                             'hours in an oral glucose '
                                             'tolerance test',
                                             'Diastolic blood pressure (mm Hg)',
                                             'Triceps skin fold thickness (mm)',
                                             '2-Hour serum insulin (mu U/ml)',
                                             'Body mass index (weight in '
                                             'kg/(height in m)^2)',
                                             'Diabetes pedigre...
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+'))),
                ('actual_estimator',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=1000,
                                    multi_class='auto', n_jobs=None,
                                    penalty='l2', random_state=123,
                                    solver='lbfgs', tol=0.0001, verbose=0,
                                    warm_start=False))],
         verbose=False)

In [ ]:
# save pipeline
save_model(best, 'my_first_pipeline')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['Number of times pregnant',
                                              'Plasma glucose concentration a 2 '
                                              'hours in an oral glucose '
                                              'tolerance test',
                                              'Diastolic blood pressure (mm Hg)',
                                              'Triceps skin fold thickness (mm)',
                                              '2-Hour serum insulin (mu U/ml)',
                                              'Body mass index (weight in '
                                              'kg/(height in m)^2)',
                                              'Diabetes pedigre...
                  TransformerWrapper(exclude=None, include=None,
                                     transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+'))),
                 ('trained_model',
                  LogisticRegression(C=1.0, class_weight=None, dual=False,
                                     fit_intercept=True, intercept_scaling=1,
                                     l1_ratio=None, max_iter=1000,
                                     multi_class='auto', n_jobs=None,
                                     penalty='l2', random_state=123,
                                     solver='lbfgs', tol=0.0001, verbose=0,
                                     warm_start=False))],
          verbose=False),
 'my_first_pipeline.pkl')

In [ ]:
# load pipeline
loaded_best_pipeline = load_model('my_first_pipeline')
loaded_best_pipeline

Transformation Pipeline and Model Successfully Loaded

Pipeline(memory=FastMemory(location=/tmp/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Number of times pregnant',
                                             'Plasma glucose concentration a 2 '
                                             'hours in an oral glucose '
                                             'tolerance test',
                                             'Diastolic blood pressure (mm Hg)',
                                             'Triceps skin fold thickness (mm)',
                                             '2-Hour serum insulin (mu U/ml)',
                                             'Body mass index (weight in '
                                             'kg/(height in m)^2)',
                                             'Diab...
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+'))),
                ('trained_model',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=1000,
                                    multi_class='auto', n_jobs=None,
                                    penalty='l2', random_state=123,
                                    solver='lbfgs', tol=0.0001, verbose=0,
                                    warm_start=False))],
         verbose=False)